version: '3.7'
services:
  openvpn:
    userns_mode: "host"
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    ports:
     - "1194:1194/udp"
    restart: unless-stopped
    volumes:
     - ./conf:/etc/openvpn
